### ISSUE TITLE
Saving canned queries does not work

### ISSUE THREAD

**Issue by tjk911** [next-LI/datasette-live-config#4]

**Comment by tjk911** [comment]
Initially, the variable wasn't defined. That's been [added now](d904cb69d8ab79d0cb9f306e435063e7323445a9) but /db/query_name does not work, as well as query names being replaced by int values. 

Suspect two issues:
1. Saving is being wonky
2. Saved metadata format might not be correct

Worth mentioning I'm not sure [this](d904cb69d8ab79d0cb9f306e435063e7323445a9) is working the way it should either.

**Comment by tjk911** [comment]
Tentatively figured out the issue - datasette expects queries to be objects of objects (dicts of dicts), but right now they're passed in as a list of objects. 

Need to figure out the form generation part as well, as the form generation script currently expects a list from the schema.

**Comment by brandonrobertz** [comment]
> Tentatively figured out the issue - datasette expects queries to be objects of objects (dicts of dicts), but right now they're passed in as a list of objects.
>
> Need to figure out the form generation part as well, as the form generation script currently expects a list from the schema.

Everything in the form needs to be an array of objects (this is a limitation of using JSON Schema). All the processing from JSONSchema version to Datasette version (key-value) happens in `schema.js`.

Here's the code for JSONSchema (array of objects) to Datasette:
https://github.com/next-LI/datasette-live-config/blob/main/config-ed/src/components/config/schema.js#L304

And the Datasette version to JSONSchema:
https://github.com/next-LI/datasette-live-config/blob/main/config-ed/src/components/config/schema.js#L398

😎

**Comment by tjk911** [comment]
Woops. Fixed the obj <-> array issue, but I now suspect canned queries are being saved in the wrong spot.

Currently, they're a tableSchema property, but it looks like they are actually a [dbSchema property instead](https://github.com/simonw/datasette/blob/main/tests/fixtures.py).

**Comment by tjk911** [comment]
Tested, fixed, merged. 7efc8aa
